script_dir := .

disableBell:
	sudo ./${script_dir}/look_and_behavior.sh disable_login_bell

laptopWalls:
	sudo ./backgrounds.sh SetLaptop

desktopWalls:
	sudo ./backgrounds.sh SetDesktop

_loginWall:
	sudo ./backgrounds.sh SetLoginBG
