#!/bin/bash

# Run this to be prompted for your ssh password; once done, you won't have to
# type it again for the rest of the session. This is a workaround to keep
# yourself from typing your password every time you do something with
# mercurial or git.

echo
echo '##############################'
echo '#########  SSH Init ##########'
echo '##############################'
echo 'If successful, you should not need to enter your password every time you'
echo 'ssh for the rest of this session.'
echo

eval $(ssh-agent)
echo 'Adding bash as ssh agent...'

ssh-add # $pass_var

bash -i
echo
exit
