#!/bin/bash
# A short script for opening files in Windows from WSL. 
# Example: > start file.pdf

cmd.exe /c start "Lanuching from BASH" "$*"

# This won't work properly if Windows can't find the file you want to use.
# The easiest way around this is to make a directory in Windows somewhere,
# symlink it, and keep your work in there. As long as the file is in a Windows
# folder, a command like "start test.html" will open properly in your default
# web browser.
