name: work
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - hatch
  - ipykernel
  - numpy
  - pip
  - pytest
  - python>=3.10.9
  - scipy
  - tqdm
  - pip:
      - jupytext
      - matplotlib
      - pytest-cov
