#!/bin/bash
# make these python functions and call individual ones!


rsync -va [in dir] [out dir] # to merge directories


# system reminders
- /dev/ is for DEVices! Look for webcam around /dev/video0
- sudo su and move to /etc/hosts. Add massive blocklist there!

# vim notes
h <
j v
k ^
l >

gj  - go down globally, not just logical lines.
search and replace - :%s/[search]/[replace]/g
cw  - change word
ciw - change inner word
diw - delete inner word
daw - delete outer word (with surrounding spaces)
das - same, for sentence
dap - same, for paragraph
.   - repeat command
A+[text] - append text to end of line
a   - append text after cursor
o   - newline below cursor
O   - newline above cursor
---------------------------
macros:
qw <macro> q
run command with @w (can change w to any mapping)
----------------------------
v   - visual
ctrl+v - visual block
G   - ground? goes to bottom.
w   - move to the right by word
c   - replace
+ esc - replaces on every line
f+<key>   - find <key>


# TODO:
- set up urxvt
- check out pywal for urxvt
- check out calcurse
- move TODO to calcurse
- make default tmux windows, with names like 'calendar', 'RSS Feed', etc.
- make newsboat functional
- bg background set shortcut script LS 01.06.17 video
- easy script for generating a new webpage from a template and adding it to the side panel if desired.

# No need to cat [file] | grep [search]
# grep operates on files
# grep [search] [file]
echo
